micronaut:
  application:
    name: micronaut-atp-demo
dataSource:
  pooled: true
  logSql: true
  dbCreate: validate
  driverClassName: oracle.jdbc.driver.OracleDriver
hibernate:
  dialect: org.hibernate.dialect.Oracle12cDialect
  format_sql: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: GraphiQL