CREATE TABLE person (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NULL,
    is_cool NUMBER(1,0) NOT NULL,
    version NUMBER(20) NOT NULL,
    date_created TIMESTAMP,
    last_updated TIMESTAMP,
    CONSTRAINT person_pk PRIMARY KEY (id)
);

CREATE TABLE hobby (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(250) NOT NULL,
    monthly_cost NUMERIC(19,2) NOT NULL,
    version NUMBER(20) NOT NULL,
    date_created TIMESTAMP,
    last_updated TIMESTAMP,
    CONSTRAINT hobby_pk PRIMARY KEY (id)
);

CREATE TABLE person_hobby (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    person_id NUMBER REFERENCES person (id),
    hobby_id NUMBER REFERENCES hobby (id),
    version NUMBER(20) NOT NULL,
    date_created TIMESTAMP,
    last_updated TIMESTAMP,
    CONSTRAINT person_hobby_pk PRIMARY KEY (id)
);